# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fde0bd5c850a226946aff1b6ef422bff9606fbd5d94db8be282c34ea9eade17a6ad4469ce59b3ce7d361818224c1f2189fb52e75f877c2893fef1c806fe5445

test:
  secret_key_base: e0f7b98e147f37c03da3dd325d83e97b969c62910a801523ed5b2064f12298db952e1ff08f2538cd86e5f967875afaa060385f0b3153688c947aae7192b0a01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
